### ISSUE TITLE
Import "ppcls.data" could not be resolved

### ISSUE THREAD

**Issue by swordLJP** [youqingxiaozhua/APViT#1]
I try to run the test of TransFER. Then I found that there is not a 'data' in Paddle.ppcls. Maybe a folder 'data' is missing in the project

**Comment by youqingxiaozhua** [comment]
Thank you for bringing this to our attention. We apologize for the mistake and have now uploaded the `ppcls.data` folder. The `/data` folder is used to store datasets, but we mistakenly ignored all data folders in our `.gitignore`. We borrowed the `ppcls.data` from PaddleClas and tested the codes. Thank you again for pointing out this error.
