### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by xiaohoua** [youqingxiaozhua/APViT#6]
Hi,I get an error when i run  tools/test.py.
the error is  : ImportError: cannot import name 'wrap_fp16_model' from 'mmcls.core'
I can't find 'wrap_fp16_model' in 'mmcls.core'.
I would be appreciated if you could help me!

**Comment by youqingxiaozhua** [comment]
No, it does not need to retrain the model for testing. Could you please provide more context details about the error message? For example, which line raised this error?

**Comment by xiaohoua** [comment]
line 13 in test.py    ( from mmcls.core import wrap_fp16_model)

**Comment by youqingxiaozhua** [comment]
I guess it may be caused by an incompatible mmcls installation. Did you install mmcls manually? Try to run `pip uninstall mmcls`，and try again.
