### ISSUE TITLE
miss function

### ISSUE THREAD

**Issue by swordLJP** [youqingxiaozhua/APViT#7]
The function 'compute_rollout_attention' in trans_fer.py is not defined. It is referenced in the function VisionTransformer.relprop().
"/APViT/Paddle/ppcls/arch/backbone/model_zoo/trans_fer.py"

**Comment by youqingxiaozhua** [comment]
This function is used for visualization. We do not tend to maintain the visualization codes. You may refer to their official repo (already replied in #3 ) to modify the visualization part.
